name: gradcon
description: A platform for PHD students

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.17
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_storage: ^10.2.17
  flutter_svg: ^1.1.0
  image_picker: ^0.8.5+3
  provider: ^6.0.3
  uuid: ^3.0.6
  flutter_staggered_grid_view: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/logo.svg

